# Generated by Django 4.0.2 on 2022-02-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0002_alter_membership_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Discount3', 'Discount3'), ('Discount2', 'Discount2'), ('Discount1', 'Discount1'), ('Monthly', 'Monthly'), ('Weekly', 'Weekly'), ('Daily', 'Daily'), ('Free', 'Free')], default='Free', max_length=30),
        ),
    ]
