# Generated by Django 4.0.2 on 2022-02-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0003_alter_membership_membership_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('cover_image', models.ImageField(null=True, upload_to='img')),
                ('banner', models.ImageField(null=True, upload_to='img')),
            ],
        ),
    ]
