# Generated by Django 4.0.2 on 2022-02-28 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0004_freegame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freegame',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='freegame',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='freegame',
            name='slug',
        ),
    ]
