# Generated by Django 4.0.2 on 2022-02-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0005_remove_freegame_banner_remove_freegame_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freegame',
            name='banner',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='freegame',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='freegame',
            name='description',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='freegame',
            name='file1',
            field=models.FileField(default=False, upload_to='file'),
        ),
        migrations.AddField(
            model_name='freegame',
            name='file2',
            field=models.FileField(default=False, upload_to='file'),
        ),
        migrations.AddField(
            model_name='freegame',
            name='file3',
            field=models.FileField(default=False, upload_to='file'),
        ),
        migrations.AddField(
            model_name='freegame',
            name='file4',
            field=models.FileField(default=False, upload_to='file'),
        ),
        migrations.AddField(
            model_name='freegame',
            name='file5',
            field=models.FileField(default=False, upload_to='file'),
        ),
        migrations.AddField(
            model_name='freegame',
            name='free_games',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='freegame',
            name='game_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freegame',
            name='ram',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freegame',
            name='slug',
            field=models.SlugField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='freegame',
            name='video',
            field=models.FileField(default=False, upload_to='img/videos'),
        ),
    ]
