# Generated by Django 4.0.2 on 2022-03-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0006_freegame_banner_freegame_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freegame',
            name='category',
            field=models.ManyToManyField(related_name='game', to='gameapp.Category'),
        ),
    ]
